[camera_android_camerax][video_player_android] Suppresses deprecation of the `SurfaceProducer.Callback.onSurfaceDestroyed` method (#8388)
See https://github.com/flutter/flutter/issues/161256

This was causing errors with the Flutter->Packages roller:

```
> Task :camera_android_camerax:compileDebugJavaWithJavac
/b/s/w/ir/x/w/packages/packages/camera/camera_android_camerax/android/src/main/java/io/flutter/plugins/camerax/PreviewHostApiImpl.java:92: warning: [removal] onSurfaceDestroyed() in Callback has been deprecated and marked for removal
              public void onSurfaceDestroyed() {
                          ^
error: warnings found and -Werror specified
1 error
1 warning
```